export const NotificationType = {
  NEW_BID: 'NEW_BID',
  BID_SELECTED: 'BID_SELECTED',
  BID_REJECTED: 'BID_REJECTED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  AGREEMENT_SENT: 'AGREEMENT_SENT',
  AGREEMENT_SIGNED: 'AGREEMENT_SIGNED',
  ESCROW_FUNDED: 'ESCROW_FUNDED',
  DEAL_COMPLETED: 'DEAL_COMPLETED',
  NEW_RESEEK: 'NEW_RESEEK',
  RATING_RECEIVED: 'RATING_RECEIVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  SYSTEM: 'SYSTEM'
} as const
export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType]
